pipeline {
    agent { label "JENKINS-AGENT" }

    environment {
        APP_NAME = "register-app-pipeline"
    }

    stages {

        stage("Cleanup Workspace") {
            steps {
                cleanWs()
            }
        }

        stage("Checkout from SCM") {
            steps {
                git branch: 'main',
                    credentialsId: 'github',
                    url: 'https://github.com/Mradul-code/gitops-register-guide.git'
            }
        }

        stage("Update the Deployment Tags") {
            steps {
                dir('gitops-register-app/gitops-register-app') {
                    sh """
                        echo "Current Directory:"
                        pwd

                        echo "Files:"
                        ls -la

                        echo "Before Update"
                        cat deployment.yaml

                        sed -i "s#${APP_NAME}:.*#${APP_NAME}:${IMAGE_TAG}#g" deployment.yaml

                        echo "After Update"
                        cat deployment.yaml
                    """
                }
            }
        }

        stage("Push the changed deployment file to Git") {
            steps {
                dir('gitops-register-app/gitops-register-app') {

                    sh """
                        git config user.name "Mradul-code"
                        git config user.email "officialcoding1@gmail.com"

                        git add deployment.yaml

                        git commit -m "Updated Deployment Manifest" || echo "No changes to commit"
                    """

                    withCredentials([gitUsernamePassword(credentialsId: 'github', gitToolName: 'Default')]) {
                        sh "git push origin main"
                    }
                }
            }
        }
    }
}
